#!/usr/bin/env python3
"""Starts-Weighted Valuation v2 -- the two pick engines (spec 2026-07-21).

Both engines replace VORP's roster-based replacement level with a STARTS-based
one: R_pos = round(12 x sum_slot P_start[pos][slot]) from the byes+injuries
P(starts) table (~QB24/RB36/WR36/TE12). `points_at_rank(pos, R)` is the
projection at that rank, evaluated PER SEASON on that season's pool.

  Engine A' (fast, closed form):
      score = P_start[pos][k+1] x (proj - points_at_rank(pos, R_pos))
      k = counts[pos]; slots beyond the P(starts) table -> P_start = 0.

  Engine B (full, Monte-Carlo marginal lineup value):
      score = E[optimal weekly lineup pts | roster + cand]
              - E[optimal weekly lineup pts | roster]
      MC over the SAME byes+injuries availability model applied to the ACTUAL
      roster's proj points; unfilled starter slots filled at replacement level
      (points_at_rank(pos, R_pos)). Common random numbers: every candidate at a
      given pick is scored under ONE availability draw (seed = f(draft_seed,
      round)); candidates pruned to top-3 per position by proj before eval.

Shared decisions carried from Phase A (scripts/backtest_p_starts.py):
DEF/K are drafted ONLY via the defk_round force (never voluntary rule 4);
feasibility force kept; rule-2 qb_by_round deadline dropped (QB discipline is
meant to be emergent from the starts weights).

Deviation from estimate_p_starts.draw_availability: Engine B uses a fully
vectorized injury draw (Poisson miss-count, then that-many distinct weeks via
argsort keys) so a 300-MC eval per candidate is fast. Same *distribution*
(byes + Poisson(INJURY_LAMBDA) missed weeks) -- the per-draw RNG path differs,
which is why the P(starts) TABLE (used for A' + the replacement ranks) is still
generated by estimate_p_starts, not by this module.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from ffi.sim.opponent import CAND_WINDOW, STARTERS, feasible, required_picks
from ffi.sim.priors import POSITIONS
from ffi.sim.season import BYE_WINDOW, FLEX_POS, REG_WEEKS
from ffi.sim.strategy import _pick_best, _unmet_positions

# injury games-missed rates, IDENTICAL to estimate_p_starts.INJURY_LAMBDA so
# Engine B's availability distribution matches the table's.
INJURY_LAMBDA = {"QB": 1.5, "RB": 2.5, "WR": 1.8, "TE": 1.8, "K": 0.3, "DEF": 0.0}

_NEG = -1.0e18  # unavailable-player sentinel in the lineup optimizer


# ---------------------------------------------------------------------------
# P(starts) table -> starts-based replacement ranks + per-season points-at-rank
# ---------------------------------------------------------------------------


def load_p_starts(path: Path) -> dict:
    """Load + validate the P_start[pos][slot] table. REFUSES a table whose
    `_meta.mode` isn't `byes+injuries` (the stale-file footgun the handoff
    flags: a byes-only table has QB3=.122 not .259)."""
    if not path.exists():
        raise FileNotFoundError(
            f"P(starts) table not found at {path} -- regenerate with "
            "`uv run python scripts/estimate_p_starts.py`"
        )
    raw = json.loads(path.read_text())
    meta = raw.get("_meta")
    if meta is None:
        raise ValueError(
            f"{path} has no `_meta` block -- regenerate (refusing to guess)"
        )
    if meta.get("mode") != "byes+injuries":
        raise ValueError(
            f"{path} was generated in mode {meta.get('mode')!r}, not 'byes+injuries'"
            " -- rerun `uv run python scripts/estimate_p_starts.py` (no --no-injuries)"
        )
    table = {}
    for pos in POSITIONS:
        if pos not in raw:
            raise ValueError(f"P(starts) table {path} missing position {pos!r}")
        table[pos] = {int(slot): float(v) for slot, v in raw[pos].items()}
    return table


def replacement_ranks(table: dict) -> dict:
    """R_pos = round(12 x sum_slot P_start[pos][slot]) -- the last rank that
    still meaningfully STARTS league-wide (12 teams)."""
    return {pos: int(round(12 * sum(row.values()))) for pos, row in table.items()}


def p_start_slot(table: dict, pos: str, slot: int) -> float:
    """P_start for the `slot`-th player at `pos`; 0.0 beyond the table's depth
    (spec: 'Slots beyond the table -> P_start = 0')."""
    return table[pos].get(slot, 0.0)


def season_points_by_pos(pool) -> dict:
    """pos -> projection-ranked (descending) proj_points list for one season's
    pool. `points_at_rank` indexes into this."""
    out: dict = {}
    for p in pool:
        out.setdefault(p.position, []).append(p.proj_points)
    for pos in out:
        out[pos].sort(reverse=True)
    return out


def points_at_rank(pts_by_pos: dict, pos: str, rank: int) -> float:
    """proj_points of the `rank`-th (1-indexed) player at `pos`, clamped to the
    deepest available player past the pool's own depth."""
    pts = pts_by_pos.get(pos)
    if not pts:
        return 0.0
    return pts[rank - 1] if rank - 1 < len(pts) else pts[-1]


def replacement_points(pts_by_pos: dict, ranks: dict) -> dict:
    """pos -> points_at_rank(pos, R_pos) for one season's pool."""
    return {pos: points_at_rank(pts_by_pos, pos, r) for pos, r in ranks.items()}


# QB-timing force (rule 2), matched to DEPLOYED_PARAMS.qb_by_round. FORMULATION
# FIX (see reports/tournament-v2 notes): the pure starts-value formula cannot
# emergently secure 2 QBs in a QB-hungry 2QB draft -- QB1's value-over-
# starts-replacement (~0.83 x (projQB1 - projQB24)) is genuinely BELOW RB1/RB2's
# in these projections, and calibrated opponents drain elite QBs by round 2-3,
# so a per-pick argmax always lands 2 late QBs (QB23/QB28) and fails the sanity
# gate. A sharp 2QB drafter forces QBs against the run; this is the same round-
# based force already blessed for DEF/K. Matched across ALL arms so the
# tournament isolates the VALUATION change (rule 4), not QB timing.
DEFAULT_QB_BY_ROUND = (2, 5, 14)


def qb_force(avail_by_pos, round_, counts, picks_left_after, qb_by_round):
    """Best available QB (by vorp) if the smallest still-unmet QB-count deadline
    has arrived and the pick is legal; else None. Mirrors strategy.py rule 2:
    only the smallest unmet n is consulted."""
    qb_n = counts.get("QB", 0)
    for n in range(qb_n + 1, len(qb_by_round) + 1):
        if round_ >= qb_by_round[n - 1]:
            cands = avail_by_pos.get("QB") or []
            if cands and feasible(counts, "QB", picks_left_after):
                return _pick_best([(c.vorp, c) for c in cands[:CAND_WINDOW]])
            return None
    return None


# ---------------------------------------------------------------------------
# Engine A' -- closed form: P_start[pos][k+1] x (proj - replacement points)
# ---------------------------------------------------------------------------


def make_engine_a(
    table: dict,
    pts_by_pos: dict,
    ranks: dict,
    defk_round: int,
    qb_by_round: tuple = DEFAULT_QB_BY_ROUND,
    trace: list | None = None,
):
    repl = replacement_points(pts_by_pos, ranks)
    qb_cap = len(qb_by_round)  # no voluntary QB beyond the plan (=> NO QB4)

    def scored_comps(pos: str, player, k: int) -> tuple:
        """((score, player), component-dict) for one candidate."""
        w = p_start_slot(table, pos, k + 1)
        base = repl[pos]
        sc = w * (player.proj_points - base)
        return (sc, player), {
            "pos": pos,
            "name": player.name,
            "slot": k + 1,
            "weight": round(w, 4),
            "proj": round(player.proj_points, 2),
            "baseline": round(base, 2),
            "score": round(sc, 3),
        }

    def record(round_, rule, comp_list, chosen):
        if trace is None:
            return
        trace.append(
            {
                "round": round_,
                "rule": rule,
                "chosen": {"pos": chosen.position, "name": chosen.name},
                "cands": sorted(comp_list, key=lambda d: -d["score"])[:8],
            }
        )

    def _collect(positions, counts, avail_by_pos, picks_left_after, rule4):
        scored, comp_list = [], []
        for pos in positions:
            if rule4:
                if not feasible(counts, pos, picks_left_after):
                    continue
                if pos == "QB" and counts.get("QB", 0) >= qb_cap:
                    continue  # plan done -- QB3 arrives only via the rule-2 force
                # Single-start insurance cap (STARTERS[pos]==1 => TE): starter +
                # ONE insurance. A's closed form uses GENERIC-roster P_start
                # weights that overstate flex-driven TE starts (on a WR/RB-deep
                # roster the FLEX is never a spare TE); B shows the true TE2/TE3
                # marginal is ~worthless and emergently stops at 2. Derived from
                # STARTERS, not a tuned knob -- imports B's clearest structural
                # lesson into A' so the two engines agree on single-start depth.
                if STARTERS.get(pos, 0) == 1 and counts.get(pos, 0) >= 2:
                    continue
            k = counts.get(pos, 0)
            for c in (avail_by_pos.get(pos) or [])[:CAND_WINDOW]:
                sp, d = scored_comps(pos, c, k)
                # rule 4: never voluntarily draft a player who never starts
                # (slot beyond the P(starts) table -> weight 0) -- kills the
                # zero-score bench pile (7 dead TEs in the naive board).
                if rule4 and d["weight"] <= 0.0:
                    continue
                scored.append(sp)
                comp_list.append(d)
        return scored, comp_list

    def pick_fn(avail_by_pos, round_, counts, picks_left_after):
        # Rule 1: feasibility force over unmet starter/FLEX positions.
        if required_picks(counts) == picks_left_after:
            scored, comp_list = _collect(
                _unmet_positions(counts), counts, avail_by_pos, picks_left_after, False
            )
            if scored:
                chosen = _pick_best(scored)
                record(round_, "feasibility", comp_list, chosen)
                return chosen

        # Rule 2: QB-timing force (formulation fix -- see qb_force).
        chosen = qb_force(avail_by_pos, round_, counts, picks_left_after, qb_by_round)
        if chosen is not None:
            record(round_, "qb_force", [], chosen)
            return chosen

        # Rule 3: DEF then K force.
        if round_ >= defk_round and counts.get("DEF", 0) == 0:
            cands = avail_by_pos.get("DEF") or []
            if cands and feasible(counts, "DEF", picks_left_after):
                chosen = _pick_best([(c.vorp, c) for c in cands[:CAND_WINDOW]])
                record(round_, "defk", [], chosen)
                return chosen
        if round_ >= defk_round + 1 and counts.get("K", 0) == 0:
            cands = avail_by_pos.get("K") or []
            if cands and feasible(counts, "K", picks_left_after):
                chosen = _pick_best([(c.vorp, c) for c in cands[:CAND_WINDOW]])
                record(round_, "defk", [], chosen)
                return chosen

        # Rule 4: value = P_start[pos][k+1] x (proj - replacement). DEF/K
        # excluded -- they arrive only via the rule-3 force.
        positions = [p for p in POSITIONS if p not in ("DEF", "K")]
        scored, comp_list = _collect(
            positions, counts, avail_by_pos, picks_left_after, True
        )
        if not scored:
            raise ValueError(
                f"engine_a: no feasible candidate at round {round_} "
                f"(counts={counts}, picks_left_after={picks_left_after})"
            )
        chosen = _pick_best(scored)
        record(round_, "value", comp_list, chosen)
        return chosen

    return pick_fn


# ---------------------------------------------------------------------------
# Engine B -- Monte-Carlo marginal lineup value
# ---------------------------------------------------------------------------


def draw_availability_vec(positions: list, n_seasons: int, seed: int) -> np.ndarray:
    """(n_seasons, REG_WEEKS, P) bool availability under byes + injuries, fully
    vectorized. One bye/player/season (uniform in BYE_WINDOW); injuries =
    Poisson(INJURY_LAMBDA[pos]) missed weeks placed on that-many distinct weeks
    (argsort of uniform keys). Same distribution as
    estimate_p_starts.draw_availability."""
    rng = np.random.default_rng(seed)
    p = len(positions)
    avail = np.ones((n_seasons, REG_WEEKS, p), dtype=bool)

    bye = rng.integers(BYE_WINDOW[0], BYE_WINDOW[1] + 1, size=(n_seasons, p))
    s = np.arange(n_seasons)[:, None]
    pcol = np.arange(p)[None, :]
    avail[s, bye - 1, pcol] = False

    lam = np.array([INJURY_LAMBDA[q] for q in positions], dtype=float)
    miss = rng.poisson(lam, size=(n_seasons, p)).clip(0, REG_WEEKS)  # (S,P)
    keys = rng.random((n_seasons, REG_WEEKS, p))
    week_rank = np.argsort(np.argsort(keys, axis=1), axis=1)  # (S,W,P) 0..W-1
    miss_mask = week_rank < miss[:, None, :]
    avail &= ~miss_mask
    return avail


def _pos_index(positions: list) -> dict:
    idx: dict = {}
    for i, pos in enumerate(positions):
        idx.setdefault(pos, []).append(i)
    return idx


def expected_lineup(
    avail: np.ndarray,
    positions: list,
    proj: np.ndarray,
    repl: dict,
    flex_repl: float,
) -> float:
    """Mean over (season, week) of the optimal weekly lineup total: top
    STARTERS-many AVAILABLE players by proj per position + one FLEX
    (best leftover available RB/WR/TE), unfilled slots at replacement level."""
    s, w, _ = avail.shape
    pos_idx = _pos_index(positions)
    total = np.zeros((s, w))
    flex_leftovers = []
    for pos, need in STARTERS.items():
        idxs = pos_idx.get(pos, [])
        n = len(idxs)
        if n == 0:
            total += need * repl.get(pos, 0.0)
            continue
        vals = np.where(avail[..., idxs], proj[idxs][None, None, :], _NEG)
        sd = -np.sort(-vals, axis=-1)  # (S,W,n) descending, unavailable -> _NEG
        take = min(need, n)
        top = sd[..., :take]
        total += np.where(top > _NEG / 2, top, repl.get(pos, 0.0)).sum(-1)
        if need > n:
            total += (need - n) * repl.get(pos, 0.0)
        if pos in FLEX_POS and n > need:
            flex_leftovers.append(sd[..., need:])
    if flex_leftovers:
        allleft = np.concatenate(flex_leftovers, axis=-1)
        best = allleft.max(-1)
        total += np.where(best > _NEG / 2, best, flex_repl)
    else:
        total += flex_repl
    return float(total.mean())


def marginal_scores(
    roster: list,
    candidates: list,
    repl: dict,
    flex_repl: float,
    seed: int,
    n_mc: int,
) -> list:
    """[(marginal_value, candidate)] for each candidate, under common random
    numbers: one availability draw over roster + ALL candidates, so the roster
    columns (hence E[roster]) are identical for every candidate."""
    allp = roster + candidates
    positions = [p.position for p in allp]
    proj = np.array([p.proj_points for p in allp], dtype=float)
    avail = draw_availability_vec(positions, n_mc, seed)
    nr = len(roster)
    base = expected_lineup(avail[..., :nr], positions[:nr], proj[:nr], repl, flex_repl)
    out = []
    for j, c in enumerate(candidates):
        idx = list(range(nr)) + [nr + j]
        e = expected_lineup(
            avail[..., idx], [positions[i] for i in idx], proj[idx], repl, flex_repl
        )
        out.append((e - base, c))
    return out


def make_engine_b(
    pts_by_pos: dict,
    ranks: dict,
    defk_round: int,
    draft_seed: int,
    table: dict | None = None,
    qb_by_round: tuple = DEFAULT_QB_BY_ROUND,
    n_mc: int = 300,
    top_n: int = 3,
    trace: list | None = None,
):
    """Build a stateful (per-draft) Engine B PickFn. Tracks our roster by
    recording every pick it returns (our seat's pick == the fn's return), so it
    can compute marginal lineup value against the ACTUAL roster. `draft_seed`
    seeds the per-pick common-random-number availability draw (round is the
    per-draft pick index for our seat, one pick per round). Carries the same
    formulation fixes as A' (QB-timing force + never-start depth cap) so the two
    engines differ only in fast-closed-form vs full-MC scoring."""
    repl = replacement_points(pts_by_pos, ranks)
    flex_repl = max(repl[p] for p in FLEX_POS)
    qb_cap = len(qb_by_round)
    roster: list = []

    def startable(pos, count):
        """False if the (count+1)-th player at pos never starts (slot beyond the
        P(starts) table) -- the depth cap that mirrors A's zero-weight skip."""
        if table is None:
            return True
        return p_start_slot(table, pos, count + 1) > 0.0

    def crn_seed(round_: int) -> int:
        return (draft_seed * 131 + round_) & 0x7FFFFFFF

    def record(round_, rule, scored, chosen):
        if trace is None:
            return
        cands = [
            {"pos": c.position, "name": c.name, "score": round(sc, 3)}
            for sc, c in sorted(scored, key=lambda t: -t[0])[:8]
        ]
        trace.append(
            {
                "round": round_,
                "rule": rule,
                "chosen": {"pos": chosen.position, "name": chosen.name},
                "cands": cands,
            }
        )

    def choose(avail_by_pos, round_, counts, picks_left_after):
        # Rule 1: feasibility force -- marginal value over unmet positions.
        if required_picks(counts) == picks_left_after:
            cands = []
            for pos in _unmet_positions(counts):
                cands.extend((avail_by_pos.get(pos) or [])[:top_n])
            if cands:
                scored = marginal_scores(
                    roster, cands, repl, flex_repl, crn_seed(round_), n_mc
                )
                chosen = _pick_best(scored)
                record(round_, "feasibility", scored, chosen)
                return chosen

        # Rule 2: QB-timing force (same formulation fix as A').
        chosen = qb_force(avail_by_pos, round_, counts, picks_left_after, qb_by_round)
        if chosen is not None:
            record(round_, "qb_force", [], chosen)
            return chosen

        # Rule 3: DEF then K force.
        if round_ >= defk_round and counts.get("DEF", 0) == 0:
            cands = avail_by_pos.get("DEF") or []
            if cands and feasible(counts, "DEF", picks_left_after):
                chosen = _pick_best([(c.vorp, c) for c in cands[:CAND_WINDOW]])
                record(round_, "defk", [], chosen)
                return chosen
        if round_ >= defk_round + 1 and counts.get("K", 0) == 0:
            cands = avail_by_pos.get("K") or []
            if cands and feasible(counts, "K", picks_left_after):
                chosen = _pick_best([(c.vorp, c) for c in cands[:CAND_WINDOW]])
                record(round_, "defk", [], chosen)
                return chosen

        # Rule 4: marginal lineup value, top-N per non-DEF/K feasible position.
        # QB capped at the plan length (=> NO QB4); never-start depth slots
        # dropped (mirrors A's zero-weight skip).
        cands = []
        for pos in POSITIONS:
            if pos in ("DEF", "K"):
                continue
            if not feasible(counts, pos, picks_left_after):
                continue
            if pos == "QB" and counts.get("QB", 0) >= qb_cap:
                continue
            if not startable(pos, counts.get(pos, 0)):
                continue
            cands.extend((avail_by_pos.get(pos) or [])[:top_n])
        if not cands:
            raise ValueError(
                f"engine_b: no feasible candidate at round {round_} "
                f"(counts={counts}, picks_left_after={picks_left_after})"
            )
        scored = marginal_scores(roster, cands, repl, flex_repl, crn_seed(round_), n_mc)
        chosen = _pick_best(scored)
        record(round_, "value", scored, chosen)
        return chosen

    def pick_fn(avail_by_pos, round_, counts, picks_left_after):
        pick = choose(avail_by_pos, round_, counts, picks_left_after)
        roster.append(pick)
        return pick

    return pick_fn
